[package]
name = "mastermind"
version = "0.1.0"
authors = ["lorenzo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
crossterm = "0.19.0"
rand = "0.8.0"
